[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
monitor_raw = no
monitor_filters = send_on_enter

; Build options
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM

; Upload options
upload_speed = 921600
